### ISSUE TITLE
Not working in Private Browsing mode

### ISSUE THREAD

**Issue by dadler** [alex-pl/full-fullscreen#3]
Hello, thanks for your work on this add-on.  It's working fine for me in regular windows but doesn't seem to do anything in Private Browsing windows: I still see the tab bar and location field.

Firefox 48.0
OSX 10.11.6
Fullscreen+ 1.0.1

**Comment by alex-pl** [comment]
Thanks for reporting this. Add-ons are disabled for private windows by default to prevent privacy issues and I didn't change that behavior.

I'll have a look into it. Probably it's only a small change.

**Comment by alex-pl** [comment]
I've published a new version 1.1 that can be used in private windows.
The new version will be reviewed by Mozilla during the next days.

https://addons.mozilla.org/firefox/addon/fullscreen-plus/versions/

**Comment by dadler** [comment]
Thanks for the quick response!
