### ISSUE TITLE
Incorrect Add-on home page

### ISSUE THREAD

**Issue by dadler** [alex-pl/full-fullscreen#4]
The URL for Add-on home page on the Mozilla Add-ons page (https://addons.mozilla.org/en-US/firefox/addon/fullscreen-plus/) is wrong; it gives me a github 404.  It's using github.com/alex-pl/fullscreen-plus rather than github.com/alex-pl/full-fullscreen .

**Comment by alex-pl** [comment]
Oh, you're right! Thank you for reporting that.

I fixed it by renaming this repo according to the Add-on name.

Background: The name full-fullscreen was taken at Mozilla, so I renamed everything to fullscreen-plus - except of this repo ;).
